---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - sample.stepflow
  resources:
  - samples
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sample.stepflow
  resources:
  - samples/finalizers
  verbs:
  - update
- apiGroups:
  - sample.stepflow
  resources:
  - samples/status
  verbs:
  - get
  - patch
  - update
