# This rule is not used by the project github-go-stepflow-sample-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to sample.stepflow resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: github-go-stepflow-sample-controller
    app.kubernetes.io/managed-by: kustomize
  name: sample-viewer-role
rules:
- apiGroups:
  - sample.stepflow
  resources:
  - samples
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sample.stepflow
  resources:
  - samples/status
  verbs:
  - get
